module.exports = {
	//小程序接口请求host
	host_api:'https://zimuyunying.cn/',
	//host_api:'http://zmyy.com/',
	//code登录
	login_api_url:'wxapi/login',
	//token登录
	tokenlogin_api_url:'wxapi/tokenlogin',
	//更新用户图像
	perfectUserInfo_api_url:'wxapi/perfectUserInfo',
	//首页接口数据
	indexdata_api_url:'wxapi/indexData',
	//首页商品切换
	goodsList_api_url:'wxapi/goodsList',
	//搜索商品列表
	searchGoodsList_api_url:'wxapi/searchGoodsList',
	//商品列表数据
	goodsInsideList_api_url:'wxapi/goodsInsideList',
	//商品详情
	goodsInfo_api_url:'wxapi/goodsInfo',
	//添加至购物车
	addCard_api_url:'wxapi/addCard',
	//购物车详情
	cardInfo_api_url:'wxapi/cardInfo',
	//操作购物车物品数量
	delCardNum_api_url:'wxapi/delCardNum',
	//清空购物车 -》 新增创建订单
	createOrders_api_url:'wxapi/createOrders',
	//直接购买创建订单
	payCreatOrder_api_url:'wxapi/payCreatOrder',
	//获取订单或者所有订单的最终付款明细界面
	payOrderList_api_url:'wxapi/payOrderList',
	//订单支付提交
	payOrders_api_url:'wxapi/payOrders',
	//取消订单
	cannelOrder_api_url:'wxapi/cannelOrder',
	//订单列表
	orderList_api_url:'wxapi/orderList',
	//订单详情
	orderInfo_api_url:'wxapi/orderInfo',
	//用户信息
	userInfo_api_url:'wxapi/userInfo',
	//用户优惠券
	voucherList_api_url:'wxapi/voucherList',
	//领取优惠券
	giveVoucher_api_url:'wxapi/giveVoucher',
	//系统信息
	sysMsg_api_url:'wxapi/sysMsg',
	//消费记录
	balanceLog_api_url:'wxapi/balanceLog',
	//建议提交
	adviceFreeback_api_url:'wxapi/adviceFreeback',
	//门店服务预约
	storeServiseSub_api_url:'wxapi/storeServiseSub',
	//服务预约列表
	storesAppointment_api_url:'wxapi/storesAppointment',
	//预约内容
	storesAppointmentInfo_api_url:'wxapi/storesAppointmentInfo',
	//确认收货
	confirmGoods_api_url:'wxapi/confirmGoods',
}